const SET_LIST = 'SET_CAMERA_LIST';
const SET_RECORD = 'SET_CAMERA_RECORD';
const SET_LIST_ELEMENT = 'SET_CAMERA_LIST_ELEMENT';
const POP_LIST_ELEMENT = 'POP_CAMERA_LIST_ELEMENT';

export { SET_LIST, SET_RECORD, SET_LIST_ELEMENT, POP_LIST_ELEMENT };
