const SET_PIE_DETAILED_REPORT_DATA = 'SET_PIE_DETAILED_REPORT_DATA';
const RESET_PIE_DETAILED_REPORT_DATA = 'RESET_PIE_DETAILED_REPORT_DATA';

export default {
  SET_PIE_DETAILED_REPORT_DATA,
  RESET_PIE_DETAILED_REPORT_DATA
};
