const SET_LIST = 'SET_PARKING_LOT_LIST_CAMERA';
const SET_LIST_ELEMENT = 'SET_PARKING_LOT_LIST_ELEMENT_CAMERA';
const SET_RECORD = 'SET_PARKING_LOT_RECORD_CAMERA';

export { SET_LIST, SET_RECORD, SET_LIST_ELEMENT };
