const SET_LIST = 'SET_PARKING_SESSION_LIST';
const SET_LIST_ELEMENT = 'SET_PARKING_SESSION_LIST_ELEMENT';
const SET_RECORD = 'SET_PARKING_SESSION_RECORD';

export { SET_LIST, SET_RECORD, SET_LIST_ELEMENT };
