const SET_LIST = 'SET_PAYMENT_ACTIVITY_LOG_LIST';
const SET_LIST_ELEMENT = 'SET_PAYMENT_ACTIVITY_LOG_LIST_ELEMENT';
const SET_RECORD = 'SET_PAYMENT_ACTIVITY_LOG_RECORD';

export { SET_LIST, SET_RECORD, SET_LIST_ELEMENT };
