const SET_LIST = 'SET_SUBSCRIBER_VEHICLE_LIST';
const SET_LIST_ELEMENT = 'SET_SUBSCRIBER_VEHICLE_LIST_ELEMENT';
const SET_RECORD = 'SET_SUBSCRIBER_VEHICLE_RECORD';

export {
  SET_LIST,
  SET_RECORD,
  SET_LIST_ELEMENT
};
