const SET_LIST = 'SET_VEHICLES_LIST';
const SET_RECORD = 'SET_VEHICLES_RECORD';
const SET_LIST_ELEMENT = 'SET_VEHICLES_ELEMENT';
const POP_LIST_ELEMENT = 'POP_LIST_ELEMENT';

export {
  SET_LIST,
  SET_LIST_ELEMENT,
  SET_RECORD,
  POP_LIST_ELEMENT
};
